### ISSUE TITLE
Capture with openni2

### ISSUE THREAD

**Issue by xMutzelx** [wg-perception/capture#29]
Hi community,
when I try to run `rosrun object_recognition_capture capture --seg_z_min 0.01 -o OBJECT_NAME.bag --preview` I get this error:
```
Registration? 1
Sync? 0
Traceback (most recent call last):
  File "/root/catkin_ws/src/capture/apps/capture", line 75, in <module>
    run_plasm(options, plasm, locals=dict(plasm=plasm, segmentation=segmentation))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = Source

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = <class 'ecto_openni.OpenNICapture'>

[cell_type] = ecto_openni::OpenNICapture

[function_name] = configure

[type] = openni_wrapper::OpenNIException

[what] = openni_wrapper::OpenNIDevice::OpenNIDevice(xn::Context&, const xn::NodeInfo&, const xn::NodeInfo&, const xn::NodeInfo&, const xn::NodeInfo&) @ /tmp/binarydeb/ros-indigo-ecto-openni-0.4.0/openni_wrapper/src/openni_device.cpp @ 94 : creating depth generator failed. Reason: USB interface is not supported!
```
By default openni_launch is used, which works fine with the kinect camera. I want to use the Asus Xtion Pro Live, which needs openni2_launch. I checked the source code, but I couldn't find a flag or option to change this. I think this should be changed, not everyone uses the kinect.
Thank you for your help.

**Comment by fivef** [comment]
see #20 for a solution
