### ISSUE TITLE
object_recognition capture ?? error !!!!

### ISSUE THREAD

**Issue by Abduoit** [wg-perception/capture#31]
I did tabletop with coke detection, everything is fine. Now, I am trying to run object_recognition capture following this [tutorial](http://wg-perception.github.io/capture/index.html#ork-capture)

but when I run this 

`rosrun object_recognition_capture orb_template -o my_textured_plane`

I get the following error, the reason is the camera is not detected, I am using Kinect v2 

Any help ??
```
abdu@grasp-uoit:~$ rosrun object_recognition_capture orb_template -o my_textured_plane
Listening for key: s on imshow:save
Registration? 1
Sync? 0
Traceback (most recent call last):
  File "/home/abdu/ws/src/ork_capture/apps/orb_template", line 108, in <module>
    run_plasm(options, plasm, locals=vars())
  File "/home/abdu/ws/src/ecto/python/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = Source

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = <class 'ecto_openni.OpenNICapture'>

[cell_type] = ecto_openni::OpenNICapture

[function_name] = configure

[type] = std::runtime_error

[what] = Index out of range.0 devices found.
```

**Comment by EmilyJrxx** [comment]
Did you start your camera by running a `.launch` file? though `openni2.launch` seems unavailable for kinect v2, you can still have a try with `kinect2_bridge`.
