### ISSUE TITLE
make sphinx-doc / make: *** [sphinx-doc] Error 2

### ISSUE THREAD

**Issue by Abduoit** [wg-perception/capture#32]
HI

I am trying to install ork from this [link](http://wg-perception.github.io/object_recognition_core/install.html#building-the-documentation)

I did the following and every thing looks fine 

```
mkdir ws && cd ws
wstool init src https://raw.github.com/wg-perception/object_recognition_core/master/doc/source/ork.rosinstall.kinetic.plus
cd src && wstool update -j8
cd .. && rosdep install --from-paths src -i -y
catkin_make
source devel/setup.bash
sudo pip install -U breathe catkin-sphinx sphinxcontrib-programoutput
cd build
make doxygen
```
BUT the last step creates error as follow

Any help please ??!!

```
abdu@grasp-uoit:~/ws/build$ make sphinx-doc
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 11, in <module>
    load_entry_point('Sphinx==1.7.5', 'console_scripts', 'sphinx-build')()
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.7.5-py2.7.egg/sphinx/cmd/build.py", line 38, in main
    return build_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.7.5-py2.7.egg/sphinx/cmd/build.py", line 22, in build_main
    from sphinx import cmdline
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.7.5-py2.7.egg/sphinx/cmdline.py", line 19, in <module>
    from docutils.utils import SystemMessage
  File "/home/abdu/py3-gpu/lib/python3.5/site-packages/docutils/utils/__init__.py", line 21, in <module>
    import docutils.io
  File "/home/abdu/py3-gpu/lib/python3.5/site-packages/docutils/io.py", line 349
    (self.destination.mode, mode)), file=self._stderr)
                                        ^
SyntaxError: invalid syntax
ork_tabletop/CMakeFiles/object_recognition_tabletop-sphinx.dir/build.make:57: recipe for target 'object_recognition_tabletop-sphinx' failed
make[3]: *** [object_recognition_tabletop-sphinx] Error 1
CMakeFiles/Makefile2:11623: recipe for target 'ork_tabletop/CMakeFiles/object_recognition_tabletop-sphinx.dir/all' failed
make[2]: *** [ork_tabletop/CMakeFiles/object_recognition_tabletop-sphinx.dir/all] Error 2
CMakeFiles/Makefile2:530: recipe for target 'ecto/CMakeFiles/sphinx-doc.dir/rule' failed
make[1]: *** [ecto/CMakeFiles/sphinx-doc.dir/rule] Error 2
Makefile:316: recipe for target 'sphinx-doc' failed
make: *** [sphinx-doc] Error 2
```

**Comment by Abduoit** [comment]
I think I should post it here https://github.com/wg-perception/object_recognition_core/issues/53
