### ISSUE TITLE
Can I run the capture with Realsense Depth Camera?

### ISSUE THREAD

**Issue by EmilyJrxx** [wg-perception/capture#34]
Hi! I'm using a Realsense D435 Depth Camera, in order to launch the capture process i run
`roslaunch realsense2_camera rs_camera.launch`
but when i tried to run the capture process by
'rosrun object_recognition_capture orb_template -o my_textured_plane'
it gives me an `0 device found`

```
Listening for key: s on imshow:save
Registration? 1
Sync? 0
Traceback (most recent call last):
  File "/home/xxwang/ork/src/capture/apps/orb_template", line 108, in <module>
    run_plasm(options, plasm, locals=vars())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = Source

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = <class 'ecto_openni.OpenNICapture'>

[cell_type] = ecto_openni::OpenNICapture

[function_name] = configure

[type] = std::runtime_error

[what] = Index out of range.0 devices found.
```

I've noticed that in [issue #20](https://github.com/wg-perception/capture/issues/20#issuecomment-278449528) they gave a possible method to use ros topics instead of openni, though i can not understand exactly how to do that. I still want to know if it is possible to run capture with realsense camera and realsense-ros package. Thank you and forgive my poor English

**Comment by EmilyJrxx** [comment]
@vrabaud Sorry to bother, but i'm wondering if i can modify some 'names' that `createsource` outputs to make it compatible with realsense D435 or Kinect V2. I made the node 'orb_template' subscribe to rostopics published by my camera, but still cannot work like i commented in #20 . Thanks
